application: <app-id>
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_dir: assets  

- url: /css
  static_dir: assets/css

- url: /images
  static_dir: assets/images

- url: /scripts
  static_dir: assets/scripts
